name: Build Electron App

on:
  workflow_dispatch: # allows manual triggering

jobs:
  build:
    name: Build for all platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, linux, mac]
        arch: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # match your Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build Vite production
        run: npm run build

      - name: Build Electron app
        run: npx electron-builder --${{ matrix.platform }} --${{ matrix.arch }}
        env:
          CSC_LINK: ${{ secrets.CSC_LINK || '' }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD || '' }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-${{ matrix.platform }}-${{ matrix.arch }}
          path: release/
