name: Build Electron App

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Clean old node_modules & npm cache
      - name: Clean node_modules & npm cache
        run: |
          if [ -d "node_modules" ]; then rm -rf node_modules; fi
          npm cache clean --force
        shell: bash

      - name: Install dependencies
        run: npm ci
        shell: bash

      # On Windows, install Electron separately
      - name: Install Electron on Windows
        if: runner.os == 'Windows'
        run: npm install electron --save-dev
        shell: cmd

      # Set GH_TOKEN for macOS/Linux to prevent GitHub publish error
      - name: Skip GH publishing if secret missing
        run: echo "GH_TOKEN=skip" >> $GITHUB_ENV
        if: ${{ matrix.os != 'windows' }}

      # Build Electron app
      - name: Build Electron app
        run: npm run dist
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: dist/*
