name: Build Electron App
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            build-args: --linux --x64
          - os: ubuntu-latest
            arch: arm64
            build-args: --linux --arm64
          - os: windows-latest
            arch: x64
            build-args: --win
          - os: macos-latest
            arch: universal
            build-args: --mac --x64 --arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Clean node_modules & npm cache
        run: |
          if [ -d "node_modules" ]; then rm -rf node_modules; fi
          npm cache clean --force
        shell: bash
      - name: Install dependencies
        run: npm install
        shell: bash
        continue-on-error: false
      - name: Install Electron on Windows
        if: runner.os == 'Windows'
        run: npm install electron --save-dev
        shell: cmd
        continue-on-error: false
      - name: Skip GH publishing if secret missing
        run: echo "GH_TOKEN=skip" >> $GITHUB_ENV
        if: ${{ matrix.os != 'windows-latest' }}
      - name: Build Electron app
        run: npx electron-builder ${{ matrix.build-args }}
        shell: bash
        continue-on-error: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-build
          path: dist/*
